apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: bookworm
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""
    - name: actorStateStore
      value: "true"
    - name: outboxPublishPubsub
      value: "pubsub"
    - name: outboxInboxPubsub
      value: "pubsub"
    - name: outboxPublishTopic
      value: "outbox"
